-- CREATE TABLE STUDENTS (FNAME VARCHAR(50), LNAME VARCHAR(50), BIRTH_DATE DATE);
-- INSERT INTO STUDENTS
-- VALUES
-- ('Marc', 'Benichou', '02/11/1998'),
-- ('Yoan', 'Cohen', '03/12/2010'),
-- ('Lea', 'Benichou', '27/07/1987'),
-- ('Amelia', 'Dux', '07/04/1996'),
-- ('David', 'Grez', '14/06/2003'),
-- ('Omer', 'Simpson', '03/10/1980')

-- INSERT INTO STUDENTS 
-- VALUES
-- ('Juliana', 'Schmidt', '05/02/1990');

-- SELECT * FROM STUDENTS

-- SELECT FNAME, LNAME FROM STUDENTS

-- SELECT FNAME, LNAME FROM STUDENTS WHERE ID = 2; ***

-- SELECT FNAME, LNAME FROM STUDENTS WHERE lname = 'Benichou' AND fname = 'Marc';

-- SELECT FNAME, LNAME FROM STUDENTS WHERE FNAME = 'Benichou' OR fname = 'Marc';

-- SELECT FNAME, LNAME FROM STUDENTS WHERE FNAME LIKE '%a%';

-- SELECT FNAME, LNAME FROM STUDENTS WHERE FNAME LIKE 'a%';

-- SELECT FNAME, LNAME FROM STUDENTS WHERE FNAME LIKE '%a'; 

-- SELECT FNAME, LNAME FROM STUDENTS WHERE FNAME LIKE '%%a';

-- SELECT FNAME, LNAME FROM STUDENTS WHERE ID = 1 and 3;***

-- SELECT FNAME, LNAME FROM STUDENTS WHERE birth_date >='01/01/2000';